windowrule = fullscreen on, match:class ^steam_app_1857090$
windowrule = tag -default-opacity, match:class ^steam_app_1857090$
windowrule = opacity 1 1, match:class ^steam_app_1857090$
windowrule = idle_inhibit fullscreen, match:class ^steam_app_1857090$
