# Status bar
set -g status-position top
set -g status-interval 5
setw -g monitor-bell on
set -g window-status-bell-style "fg=green"
set -g status-justify centre
set -g status-left-length 60
set -g status-right-length 100
set -g window-status-separator ""

set -gw automatic-rename on
set -gw automatic-rename-format '#(#{@tmux-status}/window-name.sh #{q:pane_tty} #{q:pane_current_command})'

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#(#{@tmux-status}/left.sh #{q:socket_path} #{q:session_name})"
set -g status-right "#{?client_prefix,#[fg=blue]PREFIX ,}#{?window_zoomed_flag,#[fg=blue]ZOOM ,}#{?#{==:#{pane_mode},copy-mode},#[fg=blue]COPY ,}#{?#{==:#{pane_mode},tree-mode},#[fg=blue]TREE ,}#(#{@tmux-status}/right.sh #{q:socket_path} #{q:session_name} #{q:pane_id} #{q:pane_mode} #{q:client_prefix} #{q:window_zoomed_flag} #{q:host})"
set -g window-status-format "\
#{?window_bell_flag,#[fg=green] 󰅸,#[fg=brightblack] } #I #W "
set -g window-status-current-format "#[fg=blue,bg=brightblack,bold]  #I #W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue
