windowrule = match:class org.telegram.desktop, tag -default-opacity
windowrule = match:class org.telegram.desktop, opacity 1 1
windowrule = match:class org.telegram.desktop, float on
windowrule = match:class org.telegram.desktop, center on
windowrule = match:class org.telegram.desktop, idle_inhibit fullscreen
windowrule = match:class org.telegram.desktop, size 450 650

