#!/usr/bin/env bash

socket_path="$1"
current_session="$2"
direction="$3"

mapfile -t sessions < <(tmux -S "$socket_path" list-sessions -F '#{session_name}')

current_index=-1
for index in "${!sessions[@]}"; do
  if [[ "${sessions[$index]}" == "$current_session" ]]; then
    current_index=$index
    break
  fi
done

if (( current_index < 0 )); then
  exit 0
fi

case "$direction" in
  prev)
    selected=("${sessions[@]:0:current_index}")
    ;;
  next)
    selected=("${sessions[@]:current_index + 1}")
    ;;
  *)
    exit 1
    ;;
esac

if (( ${#selected[@]} > 0 )); then
  reversed=()
  for (( index=${#selected[@]} - 1; index >= 0; index-- )); do
    reversed+=("${selected[$index]}")
  done

  printf ' %s' "${reversed[0]}"
  for session in "${reversed[@]:1}"; do
    printf '  %s' "$session"
  done
fi
