#!/usr/bin/env bash

line="$1"
pane_mode="$2"

copy_line_1='#[fg=blue]h/j/k/l#[fg=brightblack]: move       #[fg=blue]Space/v#[fg=brightblack]: select  #[fg=blue]Esc#[fg=brightblack]: clear   #[fg=blue]q#[fg=brightblack]: quit'
copy_line_2='#[fg=blue]C-u/C-d#[fg=brightblack]: half page  #[fg=blue]Enter/y#[fg=brightblack]: copy    #[fg=blue]/ ?#[fg=brightblack]: search'
tree_line_1='#[fg=blue]Up/Down#[fg=brightblack]: move   #[fg=blue]Enter#[fg=brightblack]: choose  #[fg=blue]+/-#[fg=brightblack]: expand/collapse  #[fg=blue]v#[fg=brightblack]: preview            #[fg=blue]q#[fg=brightblack]: quit'
tree_line_2='#[fg=blue]t/T#[fg=brightblack]: tag/clear  #[fg=blue]C-t#[fg=brightblack]: tag all   #[fg=blue]x/X#[fg=brightblack]: kill one/tagged  #[fg=blue]C-s/n#[fg=brightblack]: search/repeat'
prefix_line_1='#[fg=blue]x#[fg=brightblack]: kill   #[fg=blue]c#[fg=brightblack]: new   #[fg=blue]r#[fg=brightblack]: rename   #[fg=blue]k#[fg=brightblack]: kill   #[fg=blue]n/p#[fg=brightblack]: next/prev   #[fg=blue]s#[fg=brightblack]: tree  #[fg=blue]d#[fg=brightblack]: detach'
prefix_line_2='#[fg=blue]z#[fg=brightblack]: zoom   #[fg=blue]C#[fg=brightblack]: new   #[fg=blue]R#[fg=brightblack]: rename   #[fg=blue]K#[fg=brightblack]: kill   #[fg=blue]N/P#[fg=brightblack]: next/prev   #[fg=blue]e#[fg=brightblack]: copy  #[fg=blue]q#[fg=brightblack]: reload'

strip_tmux() {
  printf '%s' "$1" | sed -E 's/#\[[^]]*\]//g'
}

visible_width() {
  strip_tmux "$1" | awk '{ print length($0) }'
}

pair_width() {
  left="$1"
  right="$2"
  left_width="$(visible_width "$left")"
  right_width="$(visible_width "$right")"

  if (( left_width > right_width )); then
    printf '%s' "$left_width"
  else
    printf '%s' "$right_width"
  fi
}

pad_to_width() {
  text="$1"
  width="$2"
  text_width="$(visible_width "$text")"
  padding=$(( width - text_width ))

  if (( padding < 0 )); then
    padding=0
  fi

  printf '%s%*s' "$text" "$padding" ''
}

box_top() {
  text="$1"
  width="$2"
  printf '#[align=centre]#[fg=blue,dim]╭─#[default] %s #[fg=blue,dim]─╮' "$(pad_to_width "$text" "$width")"
}

box_bottom() {
  text="$1"
  width="$2"
  printf '#[align=centre]#[fg=blue,dim]╰─#[default] %s #[fg=blue,dim]─╯' "$(pad_to_width "$text" "$width")"
}

if [[ "$line" == 'init' ]]; then
  socket_path="$pane_mode"
  prefix_width="$(pair_width "$prefix_line_1" "$prefix_line_2")"
  tmux -S "$socket_path" set -gq @status-hint-prefix-1 "$(box_top "$prefix_line_1" "$prefix_width")"
  tmux -S "$socket_path" set -gq @status-hint-prefix-2 "$(box_bottom "$prefix_line_2" "$prefix_width")"
  exit 0
fi

if [[ "$pane_mode" == 'copy-mode' ]]; then
  copy_width="$(pair_width "$copy_line_1" "$copy_line_2")"
  case "$line" in
    1) box_top "$copy_line_1" "$copy_width" ;;
    2) box_bottom "$copy_line_2" "$copy_width" ;;
  esac
  exit 0
fi

if [[ "$pane_mode" == 'tree-mode' ]]; then
  tree_width="$(pair_width "$tree_line_1" "$tree_line_2")"
  case "$line" in
    1) box_top "$tree_line_1" "$tree_width" ;;
    2) box_bottom "$tree_line_2" "$tree_width" ;;
  esac
  exit 0
fi
