#!/usr/bin/env bash

socket_path="$1"
current_session="$2"
pane_id="$3"
pane_mode="$4"
client_prefix="$5"
window_zoomed_flag="$6"
host_name="$7"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

prev_sessions="$("$script_dir/session-info" "$socket_path" "$current_session" prev)"

if [[ -n "$prev_sessions" ]]; then
  printf '#[fg=brightblack]%s ' "$prev_sessions"
fi

printf '#[fg=blue]'
printf ' #[fg=brightblack]%s ' "${pane_id#%}"
if [[ "$pane_mode" == "copy-mode" ]]; then
  printf 'COPY '
fi
if [[ "$pane_mode" == "tree-mode" ]]; then
  printf 'TREE '
fi
if [[ "$window_zoomed_flag" == "1" ]]; then
  printf 'ZOOM '
fi

if [[ -n "${SSH_CONNECTION-}" || -n "${SSH_CLIENT-}" ]]; then
  printf '#[fg=brightblack]%s ' "$host_name"
fi
