# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

keybindings: vi
repl_prelude: default:general
save_session: true
use_tools: fs
mapping_tools:
  fs: 'fs_cat,fs_ls,fs_mkdir,fs_rm,fs_write'
compress_threshold: 64000
summarize_prompt: 'Compress the conversation into a concise recap preserving key decisions and context.'
summary_prompt: '[Compressed session context]: '
highlight: true

rag_template:
  Answer the query based on the context while respecting the rules. (user query, some textual context and rules, all inside xml tags)

  <context>
  __CONTEXT__
  </context>

  <rules>
  - If you don't know, just say so.
  - If you are not sure, ask for clarification.
  - Answer in the same language as the user query.
  - If the context appears unreadable or of poor quality, tell the user then answer as best as you can.
  - If the answer is not in the context but you think you know the answer, explain that to the user then answer with your own knowledge.
  - Answer directly and without using xml tags.
  </rules>

  <user_query>
  __INPUT__
  </user_query>

left_prompt:
  '{color.light_blue}󰫢  {color.dark_gray}{?session  {session} {color.cyan}{?role 󰵰 {role}}{color.dark_gray} }{color.cyan}{!session {?role 󰵰 {role} }}{?agent  {agent} }{?rag {color.yellow} {rag} }{color.green}{color.reset} '
right_prompt:
  '{color.light_blue}{?session  {?consume_tokens {consume_percent}%}}{color.reset}'

model: deepseek:deepseek-chat
clients:
- type: openai-compatible
  name: deepseek
  api_base: https://api.deepseek.com
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  models:
    - name: qwen3:4b-instruct
- type: openai
- type: claude
